### ISSUE TITLE
Interrupted System Call

### ISSUE THREAD

**Issue by theqlabs** [snare/voltron#65] opened 2015-01-14 18:40 UTC
Really trying to get this to work on a 32-bit Ubuntu 12.04 LTS VM. 
I can get everything installed/compiled/etc. "Voltron loaded" appears in a glowing red when I fire up GDB,  my .gdbinit has the source and init lines but I have two issues: 

     Starting program: myFile 9999
     Exception in thread Thread-1:
     Traceback (most recent call last):
     File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
     self.run()
     File "/usr/local/lib/python2.7/dist-packages/voltron-0.1-py2.7.egg/voltron/core.py", line 193, in run
     rfds, _, _ = select.select([serv, self.exit_pipe] + self.clients, [], [])
     error: (4, 'Interrupted system call')'

and then in my second terminal, when trying to start a view, I get:

     Error connecting to server: Connection refused

Thanks for any guidance you can provide.

**Comment by richo** [comment] 2015-01-14 19:18
I've reprod this (independantly, I actually thought I broke something).

I'm digging into this atm, however it's definitely a regression, so in the very short term you can probably wind back about ~a month of git history and have this bug go away.

**Comment by richo** [comment] 2015-01-14 19:18
Separately, you should not have the init line in your .gdbinit.

You should load voltron, load the inferior, the `voltron init`

**Comment by snare** [comment] 2015-01-15 00:32
No, it’s fine to `voltron init` in your gdbinit. Doing it after loading a target is only required for LLDB due to the way it manages the stop hooks (you add stop hooks on a per-target basis).

Thanks for looking into it Richo.

**Comment by richo** [comment] 2015-01-15 00:34
Ah! my bad.

(Interestingly, *sometimes* this issue did not happen to me when I started
my inferior, and stepped through a few instructions before init'ing voltron
and attaching some views. I really doubt they're related, but it might be a
Thing You Could Do to get moving with it.

Will hopefully make time to dig into the underlying issue this week some
time, but nfi when.

**Comment by snare** [comment] 2015-01-21 03:45
Didn't mean to close this. THANKS GITHUB. Let me know if this solves your problem, @theqlabs. Thanks!

**Comment by theqlabs** [comment] 2015-01-21 06:46
Will test again this week, got a little busy. Will post back results. Thanks guys for digging into this! Been dying to use this tool.

**Comment by theqlabs** [comment] 2015-01-22 00:08
Looks like it's still occurring, just pulled the newest commit and installed on a 32-bit Ubuntu 12.04 VM again: 
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/voltron-0.1-py2.7.egg/voltron/core.py", line 202, in run
    rfds, _, _ = select.select([serv, self.exit_pipe] + self.clients, [], [])
error: (4, 'Interrupted system call')
```

**Comment by theqlabs** [comment] 2015-01-22 00:15
Ok, it looks like if I load the inferior first (as you suggested) and then source dbgentry.py and run voltron init, I don't seem to get the Interrupted System call exception. 

And I also just got views working, this seems a little shaky but it's currently working (if I do it in the above order)

**Comment by theqlabs** [comment] 2015-01-22 00:17
The first "ni" I take in GDB, I check the views and instead of refreshing I get: Failed getting registers: Exception getting registers from debugger: Couldn't get extended state status: No such process.
 
I will try to dig into this as I have time. Am I the only one having these issues?

**Comment by richo** [comment] 2015-01-22 00:41
Wow, that's weird. I don't suppose you can bundle up a VM that does this for me to poke?

**Comment by richo** [comment] 2015-01-22 00:49
Can you try the branch at https://github.com/richo/voltron/tree/debug/theqlabs ?

It'll most likely barf about a jillion messages into your console. It seems likely that something is leaking tons of signals (especially if they're batched) and causing the bug.

**Comment by theqlabs** [comment] 2015-01-22 00:53
Sure, can do either. I can try the branch above first, if that doesn't work I'll bundle up the VM.

**Comment by snare** [comment] 2015-01-22 02:12
@theqlabs re: you being the only one having the issue, I really only use this on OS X with LLDB and it kinda only gets tested on Linux/GDB when @richo has to do something on Linux.

There's a test suite which runs some tests against the GDB CLI but they're really unreliable at the moment so you have to run them a few times and only treat a failure that occurred every time as a true failure. I've been meaning to try to do something to make these more reliable, but that might also be a good starting point.

In general if you're having issues, enable `debug_logging` in your config (as per the [configuration page](https://github.com/snare/voltron/wiki/Configuration)). You'll get `voltron_main.log` and `voltron_debugger.log` created in your `~/.voltron` dir, which are the log files for the views/clients and debugger respectively. These might be helpful in finding the issues (either for us or you).

I guess I should probably write a "troubleshooting" section for the wiki :)

**Comment by snare** [comment] 2015-01-22 02:29
GDB tests should be more reliable now. Waiting for the debugger to restart sucks.

**Comment by snare** [comment] 2015-01-22 02:30
BTW you'll also get a `tests/test.log` when you run the tests.

**Comment by snare** [comment] 2015-01-22 02:30
Which you do with `nosetests -sv` in the root of the repo, or `nosetests -sv tests/gdb_cli_tests.py` for just the GDB tests.

**Comment by snare** [comment] 2015-12-29 02:44
This will probably be resolved now since the core comms has been completely rewritten and is not using the sockets code any more

**Closed by snare** 2015-12-29 02:44 UTC
